from enum import Enum


ROTOR_I = 'EKMFLGDQVZNTOWYHXUSPAIBRCJ'
ROTOR_II = 'AJDKSIRUXBLHWTMCQGZNPYFVOE'
ROTOR_III = 'BDFHJLCPRTXVZNYEIWGAKMUSQO'
ROTOR_IV = 'ESOVPZJAYQUIRHXLNFTGKDCMWB'
ROTOR_V = 'VZBRGITYUPSDNHLXAWMJQOFECK'
ROTOR_VI = 'JPGVOUMFYQBENHZRDKASXLICTW'
ROTOR_VII = 'NZJHGRCXMYSWBOUFAIVLPEKQDT'
ROTOR_VIII = 'FKQHTLXOCBJSPDZRAMEWNIUYGV'
ROTOR_BETTA = 'LEYJVCNIXWPBQMDRTAKZGFUHOS'
ROTOR_GAMMA = 'FSOKANUERHMBTIYCWLQPZXVGJD'


class EnigmaRotors(Enum):
    ROTOR_I = ROTOR_I
    ROTOR_II = ROTOR_II
    ROTOR_III = ROTOR_III
    ROTOR_IV = ROTOR_IV
    ROTOR_V = ROTOR_V
    ROTOR_VI = ROTOR_VI
    ROTOR_VII = ROTOR_VII
    ROTOR_VIII = ROTOR_VIII
    ROTOR_BETTA = ROTOR_BETTA
    ROTOR_GAMMA = ROTOR_GAMMA
